spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    driver-class-name: oracle.jdbc.OracleDriver
    password: akash
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
server:
  port: 2023
  servlet:
    context-path: /api
